version: "3.8"
services:
    database:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "9006:3306"
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_DATABASE=to_do_app"
            - "MYSQL_USER=root"
            - "MYSQL_PASSWORD=root"
        networks:
            - app-network

    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        container_name: server
        restart: unless-stopped
        tty: true
        ports:
            - "8000:8000"
        volumes:
            - "./server:/var/www/server"
        environment:
            - "DB_HOST=database"
        depends_on:
            - database
        networks:
            - app-network

    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        container_name: client
        ports:
            - "3000:3000"
        volumes:
            - "./client:/var/www/cilent"
        restart: unless-stopped
        tty: true
        depends_on:
            - server

networks:
    app-network:
        driver: bridge
