version: "3.8"

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        environment:
            - "DB_HOST=db"
            - "DB_DATABASE=todos"
            - "DB_USERNAME=root"
            - "DB_PASSWORD=root"
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/app/backend
        depends_on:
            - db
        networks:
            - app-network

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        tty: true
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app/frontend
        depends_on:
            - backend
        networks:
            - app-network

    db:
        image: mysql:5.7.22
        environment:
            - "MYSQL_DATABASE=todos"
            - "MYSQL_USER=root"
            - "MYSQL_PASSWORD=root"
            - "MYSQL_ROOT_PASSWORD=root"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
